### ISSUE TITLE
I get error.

### ISSUE THREAD

**Issue by muslimcyber26** [crskycode/NeXAS_Tool#2]
Hello, sorry to bother you. I just want to ask.. How to use the tools. I want to extract and translate the Aquarium (hololive) game.

I don't understand how to use the tools? Can you help me.

But, i got error like this:

![Nexas Config](https://github.com/crskycode/NeXAS_Tool/assets/17708101/99603a6f-8e68-4d97-8472-3a00e84068b0)

![Nexas Script](https://github.com/crskycode/NeXAS_Tool/assets/17708101/4b44704d-74cb-468f-8b31-788e2520158a)

**Comment by kdw-code** [comment]
pac files aren't scripts.
you need to extract the pac archive first with that tool (make sure to use CP_UTF8)
https://github.com/ginyoushijin/GIGA_NeXAS

Then you can use his tool to extract the scripts
